### ISSUE TITLE
Sync cannot complete with syncSkipped result when switching variants.

### ISSUE THREAD

**Issue by ampeixoto** [Nilzor/build-variant-matrix#11]
This plugin seems really useful, however it is not working in my project... When I press "OK" from the matrix dialog, I get the following exception:

```
java.lang.IllegalStateException: Sync cannot complete with syncSkipped result when switching variants.
	at com.nilsenlabs.flavormatrix.actions.old.LegacyBuildVariantUpdater$1.syncSkipped(LegacyBuildVariantUpdater.java:219)
	at com.android.tools.idea.gradle.project.sync.GradleSyncInvokerImpl.requestProjectSync(GradleSyncInvokerImpl.kt:49)
	at com.nilsenlabs.flavormatrix.actions.old.LegacyBuildVariantUpdater.requestGradleSync(LegacyBuildVariantUpdater.java:243)
	at com.nilsenlabs.flavormatrix.actions.SelectBuildVariantMatrixAction.actionPerformed(SelectBuildVariantMatrixAction.kt:33)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:579)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:704)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$11(IdeKeyEventDispatcher.java:704)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:256)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:701)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:590)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:473)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:462)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:227)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:804)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

Plugin v1.1.0
Android Studio Electric Eel | 2022.1.1 Patch 1

Maybe it is related with how I have my project setup...

**Comment by Nilzor** [comment]
I've encountered this once or twice myself but haven't been able to reproduce it. Can you try with Giraffe Beta 3 (or later) and  v1.2.0 of the plugin? So far only available [here](https://github.com/Nilzor/build-variant-matrix/releases) - you need too choose install from disk.

Available through the plugin repository in Android Studio in a day or two

**Comment by Nilzor** [comment]
closing as stale and unable to reproduce
