### ISSUE TITLE
Doesn't work with on Electric Eel

### ISSUE THREAD

**Issue by gcaguilar** [Nilzor/build-variant-matrix#8]
Thank you for creating the plugin, it is very useful. 
However, In the last stable version Electric Eel with plugin version 1.0.0.0, It doesn't seem to be working.

I received the following trace:

`java.lang.NoSuchMethodError: 'java.util.Set com.android.tools.idea.gradle.project.model.GradleAndroidModel.getProductFlavors()'
	at com.nilsenlabs.flavormatrix.actions.AndroidModuleHelper.createMergedDimensionList(AndroidModuleHelper.kt:34)
	at com.nilsenlabs.flavormatrix.actions.AndroidModuleHelper.createDimensionTable(AndroidModuleHelper.kt:10)
	at com.nilsenlabs.flavormatrix.actions.SelectBuildVariantMatrixAction.actionPerformed(SelectBuildVariantMatrixAction.kt:23)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:579)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:704)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$11(IdeKeyEventDispatcher.java:704)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:256)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:701)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:590)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:473)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:462)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:227)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:804)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:740)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

**Comment by Nilzor** [comment]
Noted. I'll be looking into this shortly

**Comment by Nilzor** [comment]
Issue found and a fix that works on my machine on Electric Eel Patch 1 and Flamingo Beta 1 has been built. For the imatient of you, you can download the JAR file manually [from here](https://github.com/Nilzor/build-variant-matrix/releases) before it's available through Android Studio's plugin library, which takes a couply of days.

Continued feedback from you is appreciated! Let me know especially if it doesn't work for you!

**Comment by indyfromoz** [comment]
`Electric Eel Patch 1` with the plugin installed as the JAR linked via the releases works fine for me. 

Thank you for this very handy & useful plugin, and, for fixing the issue.

**Comment by Nilzor** [comment]
Now avaliable at the plugin store and through Android Studio https://plugins.jetbrains.com/plugin/15632-build-variant-matrix-selector/versions/stable/286310

Closing the issue
